In [1]:
import cv2
import os
from keras.models import load_model
import numpy as np
from pygame import mixer
import time

pygame 2.3.0 (SDL 2.24.2, Python 3.8.8)
Hello from the pygame community. https://www.pygame.org/contribute.html


In [2]:
mixer.init()
sound = mixer.Sound('alarm.wav')

In [3]:
face = cv2.CascadeClassifier('haarcascade_frontalface_alt.xml')
leye = cv2.CascadeClassifier('haarcascade_lefteye_2splits.xml')
reye = cv2.CascadeClassifier('haarcascade_righteye_2splits.xml')


In [4]:
lbl=['Closed_eye','Open_eye',"Yawn","No_Yawn"]

In [5]:
model = load_model('cnncat2.h5')
path = os.getcwd()
cap = cv2.VideoCapture(0)
font = cv2.FONT_HERSHEY_COMPLEX_SMALL
count=0
score=0
thicc=2
rpred=[99]
lpred=[99]



In [ ]:
while(True):
    ret, frame = cap.read()
    height,width = frame.shape[:2] 

    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY) #different from RGB to grayscale as the weights implemented are different
    
    faces = face.detectMultiScale(gray,minNeighbors=5,scaleFactor=2,minSize=(24,24))
    left_eye = leye.detectMultiScale(gray)
    right_eye =  reye.detectMultiScale(gray)

    cv2.rectangle(frame, (0,height-50) , (200,height) , (0,0,0) , thickness=cv2.FILLED )
    
    for (x,y,w,h) in right_eye:
        cv2.rectangle(frame, (x,y) , (x+w,y+h) , (100,100,100) , 1)
        r_eye=frame[y:y+h,x:x+w]
        print(r_eye,r_eye.shape)
        count=count+1
        r_eye = cv2.cvtColor(r_eye,cv2.COLOR_BGR2GRAY)
        r_eye = cv2.resize(r_eye,(24,24))
        r_eye= r_eye/255
        r_eye=  r_eye.reshape(24,24,-1)
        r_eye = np.expand_dims(r_eye,axis=0)
        rpred = model.predict(r_eye)
        rpred=np.argmax(rpred,axis=1)
        if(rpred[0]==1):
            lbl='Open' 
        if(rpred[0]==0):
            lbl='Closed'
        break
    
    for (x,y,w,h) in left_eye:
        cv2.rectangle(frame, (x,y) , (x+w,y+h) , (100,100,100) , 1)
        l_eye=frame[y:y+h,x:x+w]
        count=count+1
        l_eye = cv2.cvtColor(l_eye,cv2.COLOR_BGR2GRAY)  
        l_eye = cv2.resize(l_eye,(24,24))
        
        l_eye= l_eye/255
        
        l_eye=l_eye.reshape(24,24,-1)
        
        l_eye = np.expand_dims(l_eye,axis=0)
        lpred = model.predict(l_eye)
        lpred=np.argmax(lpred,axis=1)
        if(lpred[0]==1):
            lbl='Open'   
        if(lpred[0]==0):
            lbl='Closed'
        break
    
    for (x,y,w,h) in faces:
        cv2.rectangle(frame, (x,y) , (x+w,y+h) , (100,100,100) , 1 )
        
    
    
        
        
    

    

    if(rpred[0]==0 and lpred[0]==0):
        score=score+1
        cv2.putText(frame,"Closed",(10,height-20), font, 1,(255,255,255),1,cv2.LINE_AA)
    # if(rpred[0]==1 or lpred[0]==1):
    else:
        score=score-1
        cv2.putText(frame,"Open",(10,height-20), font, 1,(255,255,255),1,cv2.LINE_AA)
    
        
    if(score<0):
        score=0   
    cv2.putText(frame,'Score:'+str(score),(100,height-20), font, 1,(255,255,255),1,cv2.LINE_AA)
    if(score>1):
        #person is feeling sleepy so we beep the alarm
        cv2.imwrite(os.path.join(path,'image.jpg'),frame)
        try:
            sound.play()
            j
        except:  # isplaying = False
            pass
        if(thicc<16):
            thicc= thicc+2
        else:
            thicc=thicc-2
            if(thicc<2):
                thicc=2
        cv2.rectangle(frame,(0,0),(width,height),(0,0,255),thicc) 
    cv2.imshow('frame',frame)
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

[[[100 100 100]
  [100 100 100]
  [100 100 100]
  ...
  [100 100 100]
  [100 100 100]
  [100 100 100]]

 [[100 100 100]
  [ 65  70  85]
  [ 64  70  85]
  ...
  [ 67  82 118]
  [ 67  82 118]
  [ 67  82 118]]

 [[100 100 100]
  [ 66  71  86]
  [ 65  71  87]
  ...
  [ 67  82 119]
  [ 67  82 119]
  [ 67  82 119]]

 ...

 [[100 100 100]
  [ 70  83 109]
  [ 70  82 107]
  ...
  [ 61  71 108]
  [ 61  71 108]
  [ 61  72 110]]

 [[100 100 100]
  [ 70  83 109]
  [ 70  82 110]
  ...
  [ 60  72 109]
  [ 61  72 110]
  [ 62  73 112]]

 [[100 100 100]
  [ 70  84 111]
  [ 70  84 111]
  ...
  [ 60  72 110]
  [ 61  73 112]
  [ 61  73 112]]] (71, 71, 3)
1/1 [==============================] - 0s 22ms/step
[[[100 100 100]
  [100 100 100]
  [100 100 100]
  ...
  [100 100 100]
  [100 100 100]
  [100 100 100]]

 [[100 100 100]
  [ 82  86 101]
  [ 85  89 103]
  ...
  [ 67  77 114]
  [ 64  75 114]
  [ 62  73 112]]

 [[100 100 100]
  [ 86  90 105]
  [ 88  92 107]
  ...
  [ 65  76 113]
  [ 65  77 115]
  [ 62  74 1

1/1 [==============================] - 0s 21ms/step
[[[100 100 100]
  [100 100 100]
  [100 100 100]
  ...
  [100 100 100]
  [100 100 100]
  [100 100 100]]

 [[100 100 100]
  [ 70  76  91]
  [ 68  75  90]
  ...
  [ 57  65 102]
  [ 56  65 102]
  [ 57  66 103]]

 [[100 100 100]
  [ 73  80  94]
  [ 70  76  91]
  ...
  [ 58  66 104]
  [ 57  66 103]
  [ 56  66 103]]

 ...

 [[100 100 100]
  [ 54  65  87]
  [ 52  62  85]
  ...
  [ 38  44  73]
  [ 37  44  73]
  [ 36  43  74]]

 [[100 100 100]
  [ 57  67  91]
  [ 53  63  87]
  ...
  [ 38  45  74]
  [ 38  46  76]
  [ 37  45  76]]

 [[100 100 100]
  [ 59  69  94]
  [ 56  65  90]
  ...
  [ 41  49  78]
  [ 41  48  78]
  [ 39  47  78]]] (66, 66, 3)
1/1 [==============================] - 0s 20ms/step
[[[100 100 100]
  [100 100 100]
  [100 100 100]
  ...
  [100 100 100]
  [100 100 100]
  [100 100 100]]

 [[100 100 100]
  [ 69  76  91]
  [ 65  73  87]
  ...
  [ 56  67 102]
  [ 58  68 103]
  [ 58  68 103]]

 [[100 100 100]
  [ 71  77  92]
  [ 66  74  88

1/1 [==============================] - 0s 20ms/step
[[[100 100 100]
  [100 100 100]
  [100 100 100]
  ...
  [100 100 100]
  [100 100 100]
  [100 100 100]]

 [[100 100 100]
  [ 78  83  98]
  [ 76  81  98]
  ...
  [ 52  63  97]
  [ 53  64  98]
  [ 54  65  99]]

 [[100 100 100]
  [ 83  87 103]
  [ 81  86 103]
  ...
  [ 53  64  98]
  [ 54  65 100]
  [ 55  66 101]]

 ...

 [[100 100 100]
  [ 61  72  94]
  [ 57  67  90]
  ...
  [ 48  51  75]
  [ 45  49  73]
  [ 41  46  71]]

 [[100 100 100]
  [ 64  74  97]
  [ 63  73  96]
  ...
  [ 47  51  75]
  [ 44  49  73]
  [ 44  48  74]]

 [[100 100 100]
  [ 65  75  99]
  [ 64  74  97]
  ...
  [ 46  51  75]
  [ 43  48  74]
  [ 43  48  75]]] (67, 67, 3)
1/1 [==============================] - 0s 21ms/step
[[[100 100 100]
  [100 100 100]
  [100 100 100]
  ...
  [100 100 100]
  [100 100 100]
  [100 100 100]]

 [[100 100 100]
  [ 73  80  94]
  [ 70  76  91]
  ...
  [ 56  65  98]
  [ 54  64  97]
  [ 54  64  97]]

 [[100 100 100]
  [ 76  80  96]
  [ 71  77  92

1/1 [==============================] - 0s 20ms/step
[[[100 100 100]
  [100 100 100]
  [100 100 100]
  ...
  [100 100 100]
  [100 100 100]
  [100 100 100]]

 [[100 100 100]
  [ 87  91 105]
  [ 87  91 105]
  ...
  [ 56  67 102]
  [ 56  67 102]
  [ 57  68 103]]

 [[100 100 100]
  [ 90  95 108]
  [ 88  92 107]
  ...
  [ 58  68 103]
  [ 58  68 103]
  [ 59  70 104]]

 ...

 [[100 100 100]
  [ 62  74  97]
  [ 61  73  97]
  ...
  [ 41  47  69]
  [ 40  47  70]
  [ 39  47  71]]

 [[100 100 100]
  [ 65  78 101]
  [ 64  76 101]
  ...
  [ 44  51  73]
  [ 42  49  73]
  [ 40  48  72]]

 [[100 100 100]
  [ 66  78 103]
  [ 65  77 102]
  ...
  [ 47  52  76]
  [ 44  51  76]
  [ 42  50  76]]] (68, 68, 3)
1/1 [==============================] - 0s 20ms/step
[[[100 100 100]
  [100 100 100]
  [100 100 100]
  ...
  [100 100 100]
  [100 100 100]
  [100 100 100]]

 [[100 100 100]
  [ 82  86 102]
  [ 79  83 100]
  ...
  [ 54  67  99]
  [ 53  67  99]
  [ 52  66  98]]

 [[100 100 100]
  [ 84  88 104]
  [ 79  85 101

1/1 [==============================] - 0s 20ms/step
[[[100 100 100]
  [100 100 100]
  [100 100 100]
  ...
  [100 100 100]
  [100 100 100]
  [100 100 100]]

 [[100 100 100]
  [105 109 119]
  [101 105 116]
  ...
  [ 54  65  99]
  [ 54  65 100]
  [ 55  66 101]]

 [[100 100 100]
  [107 111 121]
  [100 105 116]
  ...
  [ 55  66 100]
  [ 55  66 101]
  [ 57  67 102]]

 ...

 [[100 100 100]
  [ 61  70  91]
  [ 58  66  88]
  ...
  [ 34  42  66]
  [ 36  45  68]
  [ 37  46  70]]

 [[100 100 100]
  [ 62  72  94]
  [ 58  67  90]
  ...
  [ 36  43  67]
  [ 38  46  70]
  [ 37  45  70]]

 [[100 100 100]
  [ 62  73  96]
  [ 59  69  93]
  ...
  [ 37  44  68]
  [ 36  44  69]
  [ 36  45  71]]] (64, 64, 3)
1/1 [==============================] - 0s 21ms/step
[[[100 100 100]
  [100 100 100]
  [100 100 100]
  ...
  [100 100 100]
  [100 100 100]
  [100 100 100]]

 [[100 100 100]
  [101 106 118]
  [100 104 117]
  ...
  [ 55  67  99]
  [ 57  68 100]
  [ 58  69 101]]

 [[100 100 100]
  [102 107 120]
  [101 106 118

1/1 [==============================] - 0s 20ms/step
[[[100 100 100]
  [100 100 100]
  [100 100 100]
  ...
  [100 100 100]
  [100 100 100]
  [100 100 100]]

 [[100 100 100]
  [ 65  73  95]
  [ 63  72  93]
  ...
  [ 61  72 106]
  [ 62  73 108]
  [ 62  73 108]]

 [[100 100 100]
  [ 66  74  96]
  [ 63  72  93]
  ...
  [ 63  74 109]
  [ 63  74 109]
  [ 64  75 110]]

 ...

 [[100 100 100]
  [ 58  68  95]
  [ 54  63  91]
  ...
  [ 47  59  91]
  [ 50  62  95]
  [ 54  65  99]]

 [[100 100 100]
  [ 59  69  97]
  [ 56  66  94]
  ...
  [ 48  60  92]
  [ 50  62  96]
  [ 54  65 100]]

 [[100 100 100]
  [ 60  70  98]
  [ 56  67  95]
  ...
  [ 49  61  94]
  [ 52  63  97]
  [ 55  66 101]]] (66, 66, 3)
1/1 [==============================] - 0s 20ms/step
[[[100 100 100]
  [100 100 100]
  [100 100 100]
  ...
  [100 100 100]
  [100 100 100]
  [100 100 100]]

 [[100 100 100]
  [ 66  77  94]
  [ 63  73  92]
  ...
  [ 59  72 104]
  [ 58  72 104]
  [ 58  72 104]]

 [[100 100 100]
  [ 66  78  96]
  [ 61  72  91

1/1 [==============================] - 0s 20ms/step
[[[100 100 100]
  [100 100 100]
  [100 100 100]
  ...
  [100 100 100]
  [100 100 100]
  [100 100 100]]

 [[100 100 100]
  [ 68  74  95]
  [ 66  73  95]
  ...
  [ 59  69 106]
  [ 59  69 105]
  [ 59  69 105]]

 [[100 100 100]
  [ 68  74  95]
  [ 65  72  94]
  ...
  [ 60  70 107]
  [ 59  69 105]
  [ 59  69 104]]

 ...

 [[100 100 100]
  [ 62  73 100]
  [ 60  70  98]
  ...
  [ 50  61  92]
  [ 52  63  95]
  [ 55  66 100]]

 [[100 100 100]
  [ 64  75 103]
  [ 61  72 101]
  ...
  [ 52  63  95]
  [ 54  65  99]
  [ 57  68 103]]

 [[100 100 100]
  [ 64  76 105]
  [ 63  75 104]
  ...
  [ 54  65  99]
  [ 56  67 102]
  [ 59  70 104]]] (68, 68, 3)
1/1 [==============================] - 0s 20ms/step
[[[100 100 100]
  [100 100 100]
  [100 100 100]
  ...
  [100 100 100]
  [100 100 100]
  [100 100 100]]

 [[100 100 100]
  [ 72  79  99]
  [ 69  77  98]
  ...
  [ 59  69 106]
  [ 60  70 107]
  [ 60  70 107]]

 [[100 100 100]
  [ 73  81 100]
  [ 70  78  99

1/1 [==============================] - 0s 21ms/step
[[[100 100 100]
  [100 100 100]
  [100 100 100]
  ...
  [100 100 100]
  [100 100 100]
  [100 100 100]]

 [[100 100 100]
  [ 72  78  95]
  [ 72  78  95]
  ...
  [ 61  72 106]
  [ 61  72 106]
  [ 61  72 106]]

 [[100 100 100]
  [ 74  80  97]
  [ 72  78  95]
  ...
  [ 61  72 106]
  [ 61  72 106]
  [ 61  72 106]]

 ...

 [[100 100 100]
  [ 71  84 109]
  [ 69  82 107]
  ...
  [ 52  63  97]
  [ 53  64  98]
  [ 55  66 101]]

 [[100 100 100]
  [ 72  86 110]
  [ 69  83 108]
  ...
  [ 53  64  98]
  [ 54  65  99]
  [ 56  67 102]]

 [[100 100 100]
  [ 71  85 111]
  [ 69  83 108]
  ...
  [ 54  65  99]
  [ 56  67 102]
  [ 59  70 104]]] (73, 73, 3)
1/1 [==============================] - 0s 21ms/step
[[[100 100 100]
  [100 100 100]
  [100 100 100]
  ...
  [100 100 100]
  [100 100 100]
  [100 100 100]]

 [[100 100 100]
  [ 66  70  84]
  [ 67  71  86]
  ...
  [ 56  67 102]
  [ 58  70 104]
  [ 60  71 105]]

 [[100 100 100]
  [ 68  72  87]
  [ 68  73  89

1/1 [==============================] - 0s 21ms/step
[[[100 100 100]
  [100 100 100]
  [100 100 100]
  ...
  [100 100 100]
  [100 100 100]
  [100 100 100]]

 [[100 100 100]
  [ 64  77  99]
  [ 62  74  97]
  ...
  [ 53  65 104]
  [ 52  64 103]
  [ 53  65 104]]

 [[100 100 100]
  [ 66  79 102]
  [ 63  76  99]
  ...
  [ 54  66 105]
  [ 54  66 105]
  [ 54  66 105]]

 ...

 [[100 100 100]
  [ 60  72 102]
  [ 59  71 101]
  ...
  [ 40  44  73]
  [ 40  44  73]
  [ 40  44  73]]

 [[100 100 100]
  [ 61  74 103]
  [ 60  72 102]
  ...
  [ 42  46  75]
  [ 42  46  75]
  [ 42  46  75]]

 [[100 100 100]
  [ 60  73 104]
  [ 60  72 102]
  ...
  [ 43  47  76]
  [ 44  48  77]
  [ 45  50  78]]] (67, 67, 3)
1/1 [==============================] - 0s 20ms/step
[[[100 100 100]
  [100 100 100]
  [100 100 100]
  ...
  [100 100 100]
  [100 100 100]
  [100 100 100]]

 [[100 100 100]
  [ 59  66  92]
  [ 59  66  92]
  ...
  [ 65  73 114]
  [ 64  73 114]
  [ 64  73 115]]

 [[100 100 100]
  [ 59  66  91]
  [ 58  65  90

1/1 [==============================] - 0s 20ms/step
[[[100 100 100]
  [100 100 100]
  [100 100 100]
  ...
  [100 100 100]
  [100 100 100]
  [100 100 100]]

 [[100 100 100]
  [ 87  94 112]
  [ 83  90 109]
  ...
  [ 63  73 112]
  [ 63  73 112]
  [ 63  73 112]]

 [[100 100 100]
  [ 86  93 113]
  [ 83  91 111]
  ...
  [ 65  74 113]
  [ 65  74 113]
  [ 65  74 113]]

 ...

 [[100 100 100]
  [ 81  90 113]
  [ 75  84 109]
  ...
  [ 50  59  90]
  [ 45  55  87]
  [ 43  54  86]]

 [[100 100 100]
  [ 82  93 115]
  [ 77  88 112]
  ...
  [ 46  55  87]
  [ 42  53  85]
  [ 44  55  87]]

 [[100 100 100]
  [ 81  93 116]
  [ 78  90 114]
  ...
  [ 51  60  92]
  [ 46  56  89]
  [ 46  57  90]]] (70, 70, 3)
1/1 [==============================] - 0s 22ms/step
[[[100 100 100]
  [100 100 100]
  [100 100 100]
  ...
  [100 100 100]
  [100 100 100]
  [100 100 100]]

 [[100 100 100]
  [ 76  85 106]
  [ 74  83 104]
  ...
  [ 62  71 111]
  [ 61  70 110]
  [ 59  69 108]]

 [[100 100 100]
  [ 77  86 107]
  [ 76  85 106

1/1 [==============================] - 0s 20ms/step
[[[100 100 100]
  [100 100 100]
  [100 100 100]
  ...
  [100 100 100]
  [100 100 100]
  [100 100 100]]

 [[100 100 100]
  [ 84  92 109]
  [ 80  87 105]
  ...
  [ 59  71 110]
  [ 60  72 111]
  [ 60  72 111]]

 [[100 100 100]
  [ 83  91 108]
  [ 80  87 105]
  ...
  [ 60  71 112]
  [ 60  72 111]
  [ 61  73 112]]

 ...

 [[100 100 100]
  [ 58  70  95]
  [ 56  68  93]
  ...
  [ 47  51  79]
  [ 48  52  80]
  [ 45  50  77]]

 [[100 100 100]
  [ 60  71  97]
  [ 57  69  94]
  ...
  [ 48  52  81]
  [ 47  52  80]
  [ 45  51  79]]

 [[100 100 100]
  [ 60  72  98]
  [ 59  71  97]
  ...
  [ 47  52  81]
  [ 46  52  81]
  [ 46  52  82]]] (66, 66, 3)
1/1 [==============================] - 0s 20ms/step
[[[100 100 100]
  [100 100 100]
  [100 100 100]
  ...
  [100 100 100]
  [100 100 100]
  [100 100 100]]

 [[100 100 100]
  [ 67  74  95]
  [ 64  72  93]
  ...
  [ 63  72 114]
  [ 65  73 115]
  [ 64  73 115]]

 [[100 100 100]
  [ 68  75  94]
  [ 65  72  92

1/1 [==============================] - 0s 20ms/step
[[[100 100 100]
  [100 100 100]
  [100 100 100]
  ...
  [100 100 100]
  [100 100 100]
  [100 100 100]]

 [[100 100 100]
  [ 77  85 106]
  [ 73  81 103]
  ...
  [ 65  71 114]
  [ 65  71 114]
  [ 66  71 114]]

 [[100 100 100]
  [ 78  86 107]
  [ 74  82 104]
  ...
  [ 66  73 115]
  [ 65  71 114]
  [ 66  71 114]]

 ...

 [[100 100 100]
  [ 66  75 102]
  [ 61  70  98]
  ...
  [ 44  53  81]
  [ 43  53  81]
  [ 43  51  81]]

 [[100 100 100]
  [ 69  77 105]
  [ 63  71  99]
  ...
  [ 44  54  82]
  [ 43  54  82]
  [ 45  55  84]]

 [[100 100 100]
  [ 69  78 106]
  [ 66  75 103]
  ...
  [ 46  56  84]
  [ 45  56  85]
  [ 47  57  87]]] (70, 70, 3)
1/1 [==============================] - 0s 21ms/step
[[[100 100 100]
  [100 100 100]
  [100 100 100]
  ...
  [100 100 100]
  [100 100 100]
  [100 100 100]]

 [[100 100 100]
  [ 68  77  98]
  [ 67  75  97]
  ...
  [ 64  76 113]
  [ 64  76 113]
  [ 61  74 110]]

 [[100 100 100]
  [ 69  78  99]
  [ 67  75  97

1/1 [==============================] - 0s 22ms/step
[[[100 100 100]
  [100 100 100]
  [100 100 100]
  ...
  [100 100 100]
  [100 100 100]
  [100 100 100]]

 [[100 100 100]
  [ 75  84 104]
  [ 71  80 101]
  ...
  [ 64  74 112]
  [ 66  75 113]
  [ 66  75 114]]

 [[100 100 100]
  [ 78  87 106]
  [ 74  83 103]
  ...
  [ 66  75 114]
  [ 66  75 114]
  [ 67  76 115]]

 ...

 [[100 100 100]
  [ 68  77 105]
  [ 66  75 103]
  ...
  [ 46  52  80]
  [ 46  52  81]
  [ 44  53  81]]

 [[100 100 100]
  [ 68  79 106]
  [ 66  76 104]
  ...
  [ 50  56  84]
  [ 49  56  84]
  [ 47  55  83]]

 [[100 100 100]
  [ 67  79 106]
  [ 66  77 105]
  ...
  [ 52  58  86]
  [ 51  58  87]
  [ 48  56  84]]] (70, 70, 3)
1/1 [==============================] - 0s 21ms/step
[[[100 100 100]
  [100 100 100]
  [100 100 100]
  ...
  [100 100 100]
  [100 100 100]
  [100 100 100]]

 [[100 100 100]
  [ 65  73  95]
  [ 63  72  93]
  ...
  [ 62  73 115]
  [ 62  73 115]
  [ 64  75 116]]

 [[100 100 100]
  [ 66  74  96]
  [ 63  72  93

1/1 [==============================] - 0s 21ms/step
[[[100 100 100]
  [100 100 100]
  [100 100 100]
  ...
  [100 100 100]
  [100 100 100]
  [100 100 100]]

 [[100 100 100]
  [ 66  76  97]
  [ 63  74  95]
  ...
  [ 61  73 112]
  [ 61  73 112]
  [ 62  74 113]]

 [[100 100 100]
  [ 69  78  99]
  [ 68  77  98]
  ...
  [ 60  71 112]
  [ 62  74 114]
  [ 64  75 114]]

 ...

 [[100 100 100]
  [ 67  80 108]
  [ 64  77 106]
  ...
  [ 55  61  91]
  [ 50  56  87]
  [ 45  52  85]]

 [[100 100 100]
  [ 68  81 110]
  [ 65  78 108]
  ...
  [ 54  61  91]
  [ 50  57  88]
  [ 47  55  87]]

 [[100 100 100]
  [ 72  84 113]
  [ 68  80 110]
  ...
  [ 51  59  90]
  [ 49  57  89]
  [ 45  55  87]]] (70, 70, 3)
1/1 [==============================] - 0s 20ms/step
[[[100 100 100]
  [100 100 100]
  [100 100 100]
  ...
  [100 100 100]
  [100 100 100]
  [100 100 100]]

 [[100 100 100]
  [ 72  80  99]
  [ 73  80  98]
  ...
  [ 58  70 107]
  [ 63  75 111]
  [ 60  72 109]]

 [[100 100 100]
  [ 70  78  95]
  [ 69  77  94

1/1 [==============================] - 0s 22ms/step
[[[100 100 100]
  [100 100 100]
  [100 100 100]
  ...
  [100 100 100]
  [100 100 100]
  [100 100 100]]

 [[100 100 100]
  [ 70  76  98]
  [ 67  76  97]
  ...
  [ 66  78 117]
  [ 65  76 116]
  [ 64  75 116]]

 [[100 100 100]
  [ 71  78  99]
  [ 67  76  97]
  ...
  [ 67  79 118]
  [ 66  77 117]
  [ 66  77 117]]

 ...

 [[100 100 100]
  [ 60  73 101]
  [ 57  71  99]
  ...
  [ 51  57  84]
  [ 49  56  84]
  [ 47  55  83]]

 [[100 100 100]
  [ 61  74 103]
  [ 59  71 101]
  ...
  [ 52  59  85]
  [ 50  57  85]
  [ 47  56  85]]

 [[100 100 100]
  [ 62  75 104]
  [ 60  72 102]
  ...
  [ 53  60  87]
  [ 50  59  86]
  [ 48  57  86]]] (68, 68, 3)
1/1 [==============================] - 0s 21ms/step


In [8]:
cap.release()
cv2.destroyAllWindows()