In [1]:
import cv2
import mediapipe as mp
import os
from keras.models import load_model
import numpy as np
from pygame import mixer
import time
import numpy as np

pygame 2.3.0 (SDL 2.24.2, Python 3.8.8)
Hello from the pygame community. https://www.pygame.org/contribute.html


In [2]:
cap=cv2.VideoCapture(0)
font = cv2.FONT_HERSHEY_COMPLEX_SMALL
count=0
score=0
thicc=2

In [3]:
mixer.init()
sound = mixer.Sound('alarm.wav')

In [4]:
mpDraw=mp.solutions.drawing_utils
mpFaceMesh=mp.solutions.face_mesh
facemesh=mpFaceMesh.FaceMesh(max_num_faces=1)
drawSpec=mpDraw.DrawingSpec(thickness=1,circle_radius=2)

In [5]:
model2=load_model("cnnCat2.h5")
path = os.getcwd()

In [6]:
def getRightEye(image, landmarks):
    eye_top = int(landmarks[443].y * image.shape[0])
    eye_left = int(landmarks[464].x * image.shape[1])
    eye_bottom = int(landmarks[450].y * image.shape[0])
    eye_right = int(landmarks[446].x * image.shape[1])
    right_eye = image[eye_top:eye_bottom, eye_left:eye_right]
    return right_eye

In [7]:
def getRightEyeRect(image, landmarks):
    eye_top = int(landmarks[443].y * image.shape[0])
    eye_left = int(landmarks[464].x * image.shape[1])
    eye_bottom = int(landmarks[450].y * image.shape[0])
    eye_right = int(landmarks[446].x * image.shape[1])

    cloned_image = image.copy()
    cropped_right_eye = cloned_image[eye_top:eye_bottom, eye_left:eye_right]
    h, w, _ = cropped_right_eye.shape
    x = eye_left
    y = eye_top
    return x, y, w, h

In [8]:
def getLeftEye(image, landmarks):
    eye_top = int(landmarks[223].y * image.shape[0])
    eye_left = int(landmarks[226].x * image.shape[1])
    eye_bottom = int(landmarks[230].y * image.shape[0])
    eye_right = int(landmarks[243].x * image.shape[1])
    left_eye = image[eye_top:eye_bottom, eye_left:eye_right]
    return left_eye


def getLeftEyeRect(image, landmarks):
    # eye_left landmarks (27, 23, 130, 133) ->? how to utilize z info
    eye_top = int(landmarks[223].y * image.shape[0])
    eye_left = int(landmarks[226].x * image.shape[1])
    eye_bottom = int(landmarks[230].y * image.shape[0])
    eye_right = int(landmarks[243].x * image.shape[1])

    cloned_image = image.copy()
    cropped_left_eye = cloned_image[eye_top:eye_bottom, eye_left:eye_right]
    h, w, _ = cropped_left_eye.shape

    x = eye_left
    y = eye_top
    return x, y, w, h

In [9]:
def getMouth(image, landmarks):
    mouth_top = int(landmarks[164].y * image.shape[0])
    mouth_left = int(landmarks[57].x * image.shape[1])
    mouth_bottom = int(landmarks[18].y * image.shape[0])
    mouth_right = int(landmarks[287].x * image.shape[1])
    mouth = image[mouth_top:mouth_bottom, mouth_left:mouth_right]
    return mouth


def getMouthRect(image, landmarks):
    # eye_left landmarks (27, 23, 130, 133) ->? how to utilize z info
    mouth_top = int(landmarks[164].y * image.shape[0])
    mouth_left = int(landmarks[57].x * image.shape[1])
    mouth_bottom = int(landmarks[18].y * image.shape[0])
    mouth_right = int(landmarks[287].x * image.shape[1])

    cloned_image = image.copy()
    cropped_mouth = cloned_image[mouth_top:mouth_bottom, mouth_left:mouth_right]
    h, w, _ = cropped_mouth.shape

    x = mouth_left
    y = mouth_top
    return x, y, w, h

In [10]:
lbl=['Closed_eye','Open_eye',"Yawn","No_Yawn"]

In [11]:
while True:
    success,img=cap.read()
    height,width=img.shape[:2]
    imgRGB=cv2.cvtColor(img,cv2.COLOR_BGR2RGB)
    results=facemesh.process(imgRGB)
    if results.multi_face_landmarks:
        for faceLand_Marks in results.multi_face_landmarks:
            #mpDraw.draw_landmarks(img,faceLand_Marks,mpFaceMesh.FACEMESH_LIPS,drawSpec,drawSpec)
            right_eye_img=getRightEye(img,faceLand_Marks.landmark)
            right_eye_height,right_eye_width,_=right_eye_img.shape
            xRightEye,yRightEye,rightEyeWidth,rightEyeHeight=getRightEyeRect(img,faceLand_Marks.landmark)
            cv2.rectangle(img,(xRightEye,yRightEye),(xRightEye+right_eye_width,yRightEye+right_eye_height),(200,0,0),2)
            
            left_eye_img=getLeftEye(img,faceLand_Marks.landmark)
            left_eye_height,left_eye_width,_=left_eye_img.shape
            xLeftEye,yLeftEye,leftEyeWidth,leftEyeHeight=getLeftEyeRect(img,faceLand_Marks.landmark)
            cv2.rectangle(img,(xLeftEye,yLeftEye),(xLeftEye+left_eye_width,yLeftEye+left_eye_height),(200,0,0),2)
            
            mouth_img=getMouth(img,faceLand_Marks.landmark)
            mouth_height,mouth_width,_=mouth_img.shape
            xMouth,yMouth,MouthWidth,MouthHeight=getMouthRect(img,faceLand_Marks.landmark)
            cv2.rectangle(img,(xMouth,yMouth),(xMouth+mouth_width,yMouth+mouth_height),(0,0,255),2)
            
            
            right_eye=img[yRightEye:yRightEye+right_eye_height,xRightEye:xRightEye+right_eye_width]
            
            left_eye=img[yLeftEye:yLeftEye+left_eye_height,xLeftEye:xLeftEye+left_eye_width]
            
            mouth=img[yMouth:yMouth+mouth_height,xMouth:xMouth+mouth_width]
            
            mouth=cv2.cvtColor(mouth,cv2.COLOR_BGR2GRAY)
            mouth=cv2.resize(mouth,(24,24))
            mouth=mouth/255
            mouth=mouth.reshape(24,24,-1)
            mouth=np.expand_dims(mouth,axis=0)
            mouthpred=model2.predict(mouth)
            #print(mouthpred)
            mouthpred=np.argmax(mouthpred,axis=1)
            if mouthpred[0]==4:
                #print("Yawn")
                lbl="Yawn"
            elif mouthpred[0]==3:
                #print("No_Yawn")
                lbl="No_Yawn"
            
            
            right_eye=cv2.cvtColor(right_eye,cv2.COLOR_BGR2GRAY)
            right_eye=cv2.resize(right_eye,(24,24))
            right_eye=right_eye/255
            right_eye=right_eye.reshape(24,24,-1)
            right_eye=np.expand_dims(right_eye,axis=0)
            rpred=model2.predict(right_eye)
            print(rpred)
            rpred=np.argmax(rpred,axis=1)
            if rpred[0]==2:
                lbl="Open_eye"
                print(lbl)
            elif rpred[0]==1:
                print(lbl)
                lbl="Closed_eye"
                
            
            left_eye=cv2.cvtColor(left_eye,cv2.COLOR_BGR2GRAY)
            left_eye=cv2.resize(left_eye,(24,24))
            left_eye=left_eye/255
            left_eye=left_eye.reshape(24,24,-1)
            left_eye=np.expand_dims(left_eye,axis=0)
            lpred=model2.predict(left_eye)
            lpred=np.argmax(lpred,axis=1)
            if lpred[0]==2:
                lbl="Open_eye"
            elif lpred[0]==1:
                lbl="Close_eye"
            
            
            if (rpred[0]==1 or lpred[0]==1 or mouthpred[0]==4 ):
                score=score+1
                cv2.putText(img,"Closed or Yawning",(300,height-20), font, 1,(255,255,255),1,cv2.LINE_AA)
                # if(rpred[0]==1 or lpred[0]==1):
            else:
                score=score-1
                cv2.putText(img,"Open",(10,height-20), font, 1,(255,255,255),1,cv2.LINE_AA)
                
            if(score<0):
                score=0   
            cv2.putText(img,'Score:'+str(score),(100,height-20), font, 1,(255,255,255),1,cv2.LINE_AA)
            if(score>10):
                #person is feeling sleepy so we beep the alarm
                cv2.imwrite(os.path.join(path,'image.jpg'),img)
                try:
                    sound.play()
                    j
                except:  # isplaying = False
                    pass
                if(thicc<16):
                    thicc= thicc+2
                else:
                    thicc=thicc-2
                    if(thicc<2):
                        thicc=2
                cv2.rectangle(img,(0,0),(width,height),(0,0,255),thicc) 
            

            
            
    
    
    
    
    cv2.imshow("Image",img)
    if(cv2.waitKey(20) & 0XFF==ord("d")):
        break

1/1 [==============================] - 0s 22ms/step
[[1.9212870e-04 7.3711909e-02 8.7768114e-01 3.4041949e-02 1.4372797e-02]]
Open_eye
1/1 [==============================] - 0s 23ms/step
[[1.3314946e-04 8.0703728e-02 1.3097462e-01 7.7347267e-01 1.4715837e-02]]
1/1 [==============================] - 0s 21ms/step
[[2.59397901e-04 1.24047965e-01 1.70013085e-01 6.80447519e-01
  2.52320599e-02]]
1/1 [==============================] - 0s 20ms/step
[[2.6504498e-04 1.2797253e-01 5.0457459e-02 7.9753643e-01 2.3768486e-02]]
1/1 [==============================] - 0s 21ms/step
[[2.5246170e-04 1.0462195e-01 4.3353267e-02 8.2622653e-01 2.5545776e-02]]
1/1 [==============================] - 0s 21ms/step
[[4.8179645e-04 9.9770471e-02 1.6538547e-01 6.9210148e-01 4.2260811e-02]]
1/1 [==============================] - 0s 20ms/step
[[2.0120241e-04 3.9805885e-02 7.9695392e-01 1.4143935e-01 2.1599563e-02]]
Open_eye
1/1 [==============================] - 0s 20ms/step
[[0.00052458 0.1236772  0.4333072  0.4070

1/1 [==============================] - 0s 21ms/step
[[4.6100515e-05 2.9433075e-02 9.1130561e-01 5.1877778e-02 7.3374668e-03]]
Open_eye
1/1 [==============================] - 0s 20ms/step
[[6.6260181e-05 3.7530646e-02 9.0253955e-01 5.0332543e-02 9.5309308e-03]]
Open_eye
1/1 [==============================] - 0s 21ms/step
[[3.6317178e-05 1.2887192e-02 9.5353276e-01 2.7648641e-02 5.8951834e-03]]
Open_eye
1/1 [==============================] - 0s 20ms/step
[[2.1962001e-05 8.1124380e-03 9.8148674e-01 7.1358043e-03 3.2430727e-03]]
Open_eye
1/1 [==============================] - 0s 20ms/step
[[3.8807106e-05 3.5838950e-02 9.1799289e-01 4.0310789e-02 5.8185719e-03]]
Open_eye
1/1 [==============================] - 0s 21ms/step
[[6.0445444e-05 5.5417418e-02 8.5424531e-01 8.1133910e-02 9.1429763e-03]]
Open_eye
1/1 [==============================] - 0s 20ms/step
[[6.7012443e-05 3.5475373e-02 8.2676685e-01 1.2544152e-01 1.2249226e-02]]
Open_eye
1/1 [==============================] - 0s 21ms/step
[[0

1/1 [==============================] - 0s 21ms/step
[[1.1875507e-04 1.4465562e-01 3.3943677e-01 5.0236136e-01 1.3427530e-02]]
1/1 [==============================] - 0s 20ms/step
[[1.5649146e-04 2.0980048e-01 4.0808624e-01 3.6509672e-01 1.6860066e-02]]
Open_eye
1/1 [==============================] - 0s 21ms/step
[[3.6357448e-04 2.0562203e-01 5.8649307e-01 1.8078928e-01 2.6732063e-02]]
Open_eye
1/1 [==============================] - 0s 21ms/step
[[1.4720189e-04 1.4240819e-01 5.6997532e-01 2.7121297e-01 1.6256312e-02]]
Open_eye
1/1 [==============================] - 0s 21ms/step
[[1.9602486e-04 1.0709788e-01 5.4591173e-01 3.2647213e-01 2.0322314e-02]]
Open_eye
1/1 [==============================] - 0s 21ms/step
[[0.00050327 0.29009274 0.46839914 0.21013854 0.03086629]]
Open_eye
1/1 [==============================] - 0s 21ms/step
[[9.2778442e-05 1.0645353e-01 7.8316396e-01 9.9439234e-02 1.0850572e-02]]
Open_eye
1/1 [==============================] - 0s 20ms/step
[[1.24426588e-04 1.00048013

1/1 [==============================] - 0s 20ms/step
[[8.6336193e-05 1.3276494e-01 8.2495010e-01 3.4387190e-02 7.8114420e-03]]
Open_eye
1/1 [==============================] - 0s 21ms/step
[[7.2680938e-05 1.7347051e-01 7.9609561e-01 2.3236662e-02 7.1245604e-03]]
Open_eye
1/1 [==============================] - 0s 22ms/step
[[1.8207413e-04 7.4011874e-01 1.9468752e-01 5.4678243e-02 1.0333402e-02]]
Open_eye
1/1 [==============================] - 0s 21ms/step
[[1.10422174e-04 5.67977190e-01 3.64918351e-01 5.80375195e-02
  8.95651896e-03]]
Open_eye
1/1 [==============================] - 0s 21ms/step
[[1.1780184e-04 4.8719946e-01 4.1285765e-01 9.0164535e-02 9.6605979e-03]]
Open_eye
1/1 [==============================] - 0s 22ms/step
[[1.5064856e-04 5.2747029e-01 3.7059927e-01 9.0479434e-02 1.1300425e-02]]
Open_eye
1/1 [==============================] - 0s 21ms/step
[[1.5802972e-04 6.6668326e-01 2.6724723e-01 5.6580577e-02 9.3308715e-03]]
Open_eye
1/1 [==============================] - 0s 20ms/s

1/1 [==============================] - 0s 21ms/step
[[3.2956756e-04 1.5875538e-01 6.8394780e-01 1.3422583e-01 2.2741441e-02]]
Open_eye
1/1 [==============================] - 0s 21ms/step
[[3.1113257e-06 1.8189719e-03 9.9688655e-01 4.1240663e-04 8.7906781e-04]]
Open_eye
1/1 [==============================] - 0s 20ms/step
[[8.8411534e-06 6.4797639e-03 9.8952466e-01 2.1980922e-03 1.7886843e-03]]
Open_eye
1/1 [==============================] - 0s 21ms/step
[[8.1280623e-06 8.2343034e-03 9.8772591e-01 2.1879170e-03 1.8437175e-03]]
Open_eye
1/1 [==============================] - 0s 21ms/step
[[6.8069999e-06 8.0093127e-03 9.8614562e-01 4.0402901e-03 1.7979763e-03]]
Open_eye
1/1 [==============================] - 0s 20ms/step
[[4.2305044e-05 2.0678062e-02 9.6814871e-01 6.4343014e-03 4.6966393e-03]]
Open_eye
1/1 [==============================] - 0s 21ms/step
[[8.6012533e-06 1.5684692e-02 9.8075014e-01 2.0837551e-03 1.4728040e-03]]
Open_eye
1/1 [==============================] - 0s 21ms/step
[[3

1/1 [==============================] - 0s 21ms/step
[[2.2404425e-05 9.3395954e-01 5.8198240e-02 6.6870167e-03 1.1328021e-03]]
Close_eye
1/1 [==============================] - 0s 20ms/step
[[4.5988534e-05 8.2818931e-01 1.6276743e-01 6.9566821e-03 2.0406006e-03]]
Close_eye
1/1 [==============================] - 0s 22ms/step
[[2.6623093e-05 7.8014135e-02 9.1772324e-01 2.5354850e-03 1.7004998e-03]]
Open_eye
1/1 [==============================] - 0s 21ms/step
[[6.2483878e-06 7.0046536e-03 9.9158382e-01 4.9556117e-04 9.0973359e-04]]
Open_eye
1/1 [==============================] - 0s 21ms/step
[[3.6104035e-07 7.9715392e-04 9.9895251e-01 6.6112916e-05 1.8387097e-04]]
Open_eye
1/1 [==============================] - 0s 21ms/step
[[2.2981020e-08 6.6627385e-05 9.9984848e-01 4.2522297e-05 4.2328171e-05]]
Open_eye
1/1 [==============================] - 0s 21ms/step
[[2.9496009e-08 1.2811218e-04 9.9978381e-01 4.0930950e-05 4.7150337e-05]]
Open_eye
1/1 [==============================] - 0s 20ms/step
[

1/1 [==============================] - 0s 21ms/step
[[3.8217407e-04 9.4792858e-02 2.5230139e-01 6.2144268e-01 3.1080905e-02]]
1/1 [==============================] - 0s 21ms/step
[[3.6019800e-04 8.8674471e-02 7.8731263e-01 9.8415181e-02 2.5237469e-02]]
Open_eye
1/1 [==============================] - 0s 21ms/step
[[1.8601079e-04 8.3421521e-02 2.2734071e-01 6.6664475e-01 2.2407020e-02]]
1/1 [==============================] - 0s 21ms/step
[[4.3336974e-04 1.2716109e-01 3.2614079e-01 5.1189965e-01 3.4365036e-02]]
1/1 [==============================] - 0s 21ms/step
[[3.9996390e-04 8.8033192e-02 1.3009383e-01 7.4770677e-01 3.3766322e-02]]
1/1 [==============================] - 0s 20ms/step
[[2.28971039e-04 1.14892475e-01 1.81336507e-01 6.78051114e-01
  2.54909471e-02]]
1/1 [==============================] - 0s 21ms/step
[[1.81540512e-04 1.21105105e-01 2.82866657e-01 5.75373888e-01
  2.04728320e-02]]
1/1 [==============================] - 0s 20ms/step
[[1.4103670e-04 4.3234896e-02 5.5333155e-01

1/1 [==============================] - 0s 20ms/step
[[2.5132779e-04 5.9050161e-01 2.1588671e-01 1.7912211e-01 1.4238225e-02]]
Close_eye
1/1 [==============================] - 0s 21ms/step
[[7.4717850e-06 9.9068904e-01 5.9479102e-03 2.4603633e-03 8.9517125e-04]]
Closed_eye
1/1 [==============================] - 0s 21ms/step
[[1.5875514e-04 3.7105125e-01 5.4891372e-01 6.7038991e-02 1.2837271e-02]]
Open_eye
1/1 [==============================] - 0s 20ms/step
[[1.3134502e-04 1.3011521e-01 7.5196642e-01 1.0529307e-01 1.2493958e-02]]
Open_eye
1/1 [==============================] - 0s 21ms/step
[[8.2872393e-05 1.2831028e-01 7.7202123e-01 8.9678779e-02 9.9068945e-03]]
Open_eye
1/1 [==============================] - 0s 20ms/step
[[2.2683118e-05 4.6363965e-02 9.4386005e-01 6.6827931e-03 3.0704311e-03]]
Open_eye
1/1 [==============================] - 0s 21ms/step
[[1.5586015e-04 1.4860380e-01 7.1768016e-01 1.1970231e-01 1.3857915e-02]]
Open_eye
1/1 [==============================] - 0s 21ms/step


1/1 [==============================] - 0s 21ms/step
[[1.5471339e-04 2.9515880e-01 3.3925697e-01 3.5037580e-01 1.5053718e-02]]
1/1 [==============================] - 0s 21ms/step
[[1.4033701e-04 5.0740641e-01 3.7749669e-01 1.0378006e-01 1.1176447e-02]]
Close_eye
1/1 [==============================] - 0s 21ms/step
[[1.9315481e-05 9.8413414e-01 1.0478216e-02 3.6048938e-03 1.7633062e-03]]
No_Yawn
1/1 [==============================] - 0s 21ms/step
[[1.1654360e-04 6.9126630e-01 2.6774088e-01 3.2797746e-02 8.0785118e-03]]
Close_eye
1/1 [==============================] - 0s 20ms/step
[[1.08528606e-04 7.97060788e-01 1.70584723e-01 2.59477571e-02
  6.29832456e-03]]
Yawn
1/1 [==============================] - 0s 21ms/step
[[1.1630005e-04 7.0113808e-01 2.4315955e-01 4.5955244e-02 9.6308850e-03]]
No_Yawn
1/1 [==============================] - 0s 21ms/step
[[9.4258670e-05 8.1955558e-01 1.4171055e-01 3.1957861e-02 6.6816472e-03]]
Close_eye
1/1 [==============================] - 0s 20ms/step
[[1.2448

1/1 [==============================] - 0s 20ms/step
[[2.7672638e-04 1.6699016e-01 6.5532655e-01 1.5809716e-01 1.9309314e-02]]
Open_eye
1/1 [==============================] - 0s 21ms/step
[[2.5790144e-04 4.4391289e-01 4.3122858e-01 1.0855328e-01 1.6047223e-02]]
Open_eye
1/1 [==============================] - 0s 21ms/step
[[1.3102421e-04 1.1962150e-01 6.8798172e-01 1.8045770e-01 1.1808059e-02]]
Open_eye
1/1 [==============================] - 0s 21ms/step
[[1.20610486e-04 8.06778520e-02 8.28944564e-01 7.43642002e-02
  1.58928093e-02]]
Open_eye
1/1 [==============================] - 0s 21ms/step
[[3.5970102e-04 2.6949003e-01 6.3083100e-01 7.8627340e-02 2.0691806e-02]]
Open_eye
1/1 [==============================] - 0s 21ms/step
[[1.8354766e-04 2.3471475e-01 7.1493685e-01 3.9566278e-02 1.0598547e-02]]
Open_eye
1/1 [==============================] - 0s 21ms/step
[[1.9197253e-04 4.4577292e-01 3.3504704e-01 2.0321801e-01 1.5770141e-02]]
Close_eye
1/1 [==============================] - 0s 21ms/

[[3.9072223e-05 2.5448252e-02 7.6615721e-01 1.9904058e-01 9.3148351e-03]]
Open_eye
1/1 [==============================] - 0s 22ms/step
[[4.0757146e-05 3.3264399e-02 7.8803986e-01 1.6913201e-01 9.5229233e-03]]
Open_eye
1/1 [==============================] - 0s 20ms/step
[[3.8286707e-05 2.9831031e-02 7.3103291e-01 2.3002154e-01 9.0761818e-03]]
Open_eye
1/1 [==============================] - 0s 21ms/step
[[6.6757100e-05 5.1352017e-02 7.7238983e-01 1.6480675e-01 1.1384615e-02]]
Open_eye
1/1 [==============================] - 0s 21ms/step
[[4.5052384e-05 2.5690418e-02 8.4023625e-01 1.2396800e-01 1.0060301e-02]]
Open_eye
1/1 [==============================] - 0s 21ms/step
[[6.7148554e-05 5.2953944e-02 7.3201782e-01 2.0404088e-01 1.0920116e-02]]
Open_eye
1/1 [==============================] - 0s 21ms/step
[[7.4876880e-05 3.9267637e-02 7.3202521e-01 2.1463150e-01 1.4000625e-02]]
Open_eye
1/1 [==============================] - 0s 21ms/step
[[4.4901455e-05 3.3892352e-02 6.2268680e-01 3.3231425e-

1/1 [==============================] - 0s 20ms/step
[[3.2684420e-05 3.0543903e-02 9.5362920e-01 1.2473400e-02 3.3208784e-03]]
Open_eye
1/1 [==============================] - 0s 21ms/step
[[6.4488654e-06 7.4989977e-03 9.9023509e-01 1.2549981e-03 1.0045051e-03]]
Open_eye
1/1 [==============================] - 0s 21ms/step
[[1.0758852e-05 1.0156915e-02 9.8639619e-01 1.9658217e-03 1.4703406e-03]]
Open_eye
1/1 [==============================] - 0s 21ms/step
[[4.2756419e-05 5.3687882e-02 9.3070233e-01 1.1795546e-02 3.7714529e-03]]
Open_eye
1/1 [==============================] - 0s 21ms/step
[[6.9949376e-05 1.3941440e-01 8.4252119e-01 1.3538507e-02 4.4558654e-03]]
Open_eye
1/1 [==============================] - 0s 21ms/step
[[5.1748422e-05 9.5641293e-02 8.8009167e-01 2.0004937e-02 4.2103040e-03]]
Open_eye
1/1 [==============================] - 0s 21ms/step
[[5.9081929e-05 9.1773197e-02 8.7364334e-01 2.9451372e-02 5.0730337e-03]]
Open_eye
1/1 [==============================] - 0s 21ms/step
[[5

1/1 [==============================] - 0s 21ms/step
[[3.9034680e-07 9.6208870e-04 9.9814689e-01 6.6383806e-04 2.2677961e-04]]
Open_eye
1/1 [==============================] - 0s 21ms/step
[[3.3048678e-07 8.6041505e-04 9.9843699e-01 4.8719757e-04 2.1509873e-04]]
Open_eye
1/1 [==============================] - 0s 20ms/step
[[1.6290783e-06 2.0676577e-03 9.9631929e-01 1.0699684e-03 5.4131780e-04]]
Open_eye
1/1 [==============================] - 0s 21ms/step
[[4.4347562e-06 5.3574345e-03 9.9224961e-01 1.5683176e-03 8.2019181e-04]]
Open_eye
1/1 [==============================] - 0s 20ms/step
[[3.3376962e-06 4.1351016e-03 9.9374795e-01 1.2948264e-03 8.1885274e-04]]
Open_eye
1/1 [==============================] - 0s 21ms/step
[[3.8890036e-07 5.1288633e-04 9.9915195e-01 1.0366000e-04 2.3122935e-04]]
Open_eye
1/1 [==============================] - 0s 20ms/step
[[1.3471296e-07 1.7421129e-04 9.9961889e-01 5.7610359e-05 1.4922868e-04]]
Open_eye
1/1 [==============================] - 0s 21ms/step
[[1

1/1 [==============================] - 0s 21ms/step
[[7.7278084e-05 8.0031902e-02 3.9826792e-01 5.0779486e-01 1.3827995e-02]]
1/1 [==============================] - 0s 21ms/step
[[0.00073613 0.1702921  0.32504418 0.4540081  0.04991956]]
1/1 [==============================] - 0s 21ms/step
[[4.2912603e-04 1.6511393e-01 3.3746845e-01 4.5679754e-01 4.0190917e-02]]
1/1 [==============================] - 0s 22ms/step
[[0.00055142 0.17341138 0.45495787 0.32937574 0.0417036 ]]
Open_eye
1/1 [==============================] - 0s 21ms/step
[[3.0145919e-04 1.4605980e-01 1.1673349e-01 7.0496440e-01 3.1940907e-02]]
1/1 [==============================] - 0s 21ms/step
[[1.9996890e-04 7.8849174e-02 1.3779579e-01 7.5975758e-01 2.3397543e-02]]
1/1 [==============================] - 0s 21ms/step
[[1.7048618e-04 1.7579471e-01 1.9523486e-01 6.0810876e-01 2.0691156e-02]]
1/1 [==============================] - 0s 21ms/step
[[2.9424223e-04 1.9712864e-01 4.9946842e-01 2.7484217e-01 2.8266557e-02]]
Open_eye
1/1 

1/1 [==============================] - 0s 20ms/step
[[1.01731646e-04 3.94261740e-02 7.06205130e-01 2.37664029e-01
  1.66030563e-02]]
Open_eye
1/1 [==============================] - 0s 21ms/step
[[6.9739086e-05 2.7466163e-02 8.6981714e-01 9.2051357e-02 1.0595596e-02]]
Open_eye
1/1 [==============================] - 0s 21ms/step
[[5.5399312e-05 9.4706491e-03 9.5883340e-01 2.3413869e-02 8.2267867e-03]]
Open_eye
1/1 [==============================] - 0s 20ms/step
[[1.3695366e-04 3.2688286e-02 7.6658142e-01 1.8006890e-01 2.0524414e-02]]
Open_eye
1/1 [==============================] - 0s 20ms/step
[[9.1534064e-05 1.4544491e-02 8.1863964e-01 1.5006854e-01 1.6655764e-02]]
Open_eye
1/1 [==============================] - 0s 21ms/step
[[6.1640043e-05 1.4341605e-02 9.1846913e-01 5.6669392e-02 1.0458252e-02]]
Open_eye
1/1 [==============================] - 0s 20ms/step
[[4.2729138e-05 3.1097447e-02 6.2948513e-01 3.2864970e-01 1.0725113e-02]]
Open_eye
1/1 [==============================] - 0s 21ms/s

1/1 [==============================] - 0s 21ms/step
[[6.8668337e-06 5.6100446e-03 9.9204940e-01 1.2512574e-03 1.0824647e-03]]
Open_eye
1/1 [==============================] - 0s 21ms/step
[[2.9369630e-05 1.9284859e-02 9.7349948e-01 4.3518385e-03 2.8343636e-03]]
Open_eye
1/1 [==============================] - 0s 21ms/step
[[1.0567259e-05 7.9490123e-03 9.8910224e-01 1.4875686e-03 1.4507067e-03]]
Open_eye
1/1 [==============================] - 0s 21ms/step
[[1.2833973e-05 7.7283778e-03 9.8812872e-01 2.3743270e-03 1.7556974e-03]]
Open_eye
1/1 [==============================] - 0s 21ms/step
[[1.0579852e-05 6.9195284e-03 9.9071175e-01 8.6588517e-04 1.4922417e-03]]
Open_eye
1/1 [==============================] - 0s 21ms/step
[[1.3285995e-06 1.9800619e-03 9.9701971e-01 5.2196963e-04 4.7685733e-04]]
Open_eye
1/1 [==============================] - 0s 20ms/step
[[3.2778041e-06 6.2487102e-03 9.9021685e-01 2.5832122e-03 9.4793428e-04]]
Open_eye
1/1 [==============================] - 0s 21ms/step
[[2

1/1 [==============================] - 0s 21ms/step
[[2.1177455e-05 7.8136295e-02 9.1237205e-01 7.4851932e-03 1.9853013e-03]]
Open_eye
1/1 [==============================] - 0s 20ms/step
[[1.2059152e-05 4.7411870e-02 9.4360512e-01 7.4125431e-03 1.5584286e-03]]
Open_eye
1/1 [==============================] - 0s 21ms/step
[[1.1310211e-04 4.1534197e-01 5.1881182e-01 5.6917410e-02 8.8157468e-03]]
Open_eye
1/1 [==============================] - 0s 21ms/step
[[5.7393128e-05 1.6990945e-01 7.7837378e-01 4.3338820e-02 8.3204992e-03]]
Open_eye
1/1 [==============================] - 0s 21ms/step
[[3.0133313e-05 6.7624852e-02 8.8226926e-01 4.4738218e-02 5.3375228e-03]]
Open_eye
1/1 [==============================] - 0s 20ms/step
[[3.3411136e-05 4.5054909e-02 9.1623253e-01 3.3377763e-02 5.3013968e-03]]
Open_eye
1/1 [==============================] - 0s 21ms/step
[[6.1248196e-05 1.3899939e-01 3.5306135e-01 4.9752429e-01 1.0353730e-02]]
1/1 [==============================] - 0s 20ms/step
[[1.8467085e

1/1 [==============================] - 0s 20ms/step
[[1.4430070e-05 3.2863868e-03 4.7560327e-04 9.8926252e-01 6.9610407e-03]]
1/1 [==============================] - 0s 21ms/step
[[1.1514562e-05 4.5232078e-01 8.8856218e-04 5.3927624e-01 7.5028874e-03]]
1/1 [==============================] - 0s 20ms/step
[[4.3003424e-06 9.9351269e-01 5.3070630e-03 6.7126058e-04 5.0466595e-04]]
No_Yawn
1/1 [==============================] - 0s 21ms/step
[[8.8906396e-05 9.6621595e-02 8.3058667e-01 6.2243853e-02 1.0458964e-02]]
Open_eye
1/1 [==============================] - 0s 21ms/step
[[1.5949344e-04 1.4480264e-01 2.0756964e-01 6.3043445e-01 1.7033795e-02]]
1/1 [==============================] - 0s 21ms/step
[[2.1068419e-04 1.8837394e-01 6.7149663e-01 1.2104659e-01 1.8872133e-02]]
Open_eye
1/1 [==============================] - 0s 21ms/step
[[1.0053704e-04 2.3276162e-01 7.0635468e-01 5.0308030e-02 1.0475167e-02]]
Open_eye
1/1 [==============================] - 0s 21ms/step
[[4.4095257e-05 6.4677095e-01 3

1/1 [==============================] - 0s 21ms/step
[[1.6534901e-05 9.3464136e-01 6.1816834e-02 1.7032042e-03 1.8221658e-03]]
Yawn
1/1 [==============================] - 0s 21ms/step
[[9.5917618e-05 5.8917262e-02 9.1322529e-01 1.9597555e-02 8.1640342e-03]]
Open_eye
1/1 [==============================] - 0s 21ms/step
[[1.85382421e-04 1.22271381e-01 1.06012836e-01 7.55712867e-01
  1.58174988e-02]]
1/1 [==============================] - 0s 21ms/step
[[1.62520286e-04 9.47059691e-02 1.12206995e-01 7.76940167e-01
  1.59843378e-02]]
1/1 [==============================] - 0s 21ms/step
[[3.0024524e-04 2.8409666e-01 3.4242776e-01 3.4820589e-01 2.4969449e-02]]
1/1 [==============================] - 0s 21ms/step
[[1.8891566e-04 9.5033154e-02 4.7193598e-02 8.4086245e-01 1.6721943e-02]]
1/1 [==============================] - 0s 21ms/step
[[4.3655239e-04 1.6569912e-01 1.5779541e-01 6.4292449e-01 3.3144441e-02]]
1/1 [==============================] - 0s 20ms/step
[[2.6811974e-04 2.6376647e-01 6.619988

1/1 [==============================] - 0s 21ms/step
[[7.4165570e-07 3.7871598e-04 3.8978622e-05 8.6615866e-01 1.3342299e-01]]
1/1 [==============================] - 0s 21ms/step
[[1.0252528e-06 3.0471972e-04 5.7165664e-05 9.2677873e-01 7.2858281e-02]]
1/1 [==============================] - 0s 21ms/step
[[2.1600628e-05 1.8774220e-03 5.5569893e-04 8.2802421e-01 1.6952117e-01]]
1/1 [==============================] - 0s 21ms/step
[[2.6788980e-06 4.9890095e-04 1.6579777e-04 6.8987644e-01 3.0945617e-01]]
1/1 [==============================] - 0s 21ms/step
[[1.6111700e-05 1.8218859e-03 2.6687022e-04 6.8796420e-01 3.0993101e-01]]
1/1 [==============================] - 0s 20ms/step
[[0.00153963 0.03514409 0.01606597 0.5749268  0.3723235 ]]
1/1 [==============================] - 0s 20ms/step
[[1.1227213e-06 3.0580407e-04 9.2908813e-05 8.9984566e-01 9.9754572e-02]]
1/1 [==============================] - 0s 20ms/step
[[6.8691446e-07 2.0386366e-04 6.3690626e-05 9.5667154e-01 4.3060228e-02]]
1/1 [==

1/1 [==============================] - 0s 21ms/step
[[9.6124386e-05 6.5397537e-01 2.7128562e-01 6.5376908e-02 9.2660105e-03]]
Open_eye
1/1 [==============================] - 0s 21ms/step
[[1.3878933e-04 1.6405404e-01 7.6191550e-01 5.9770018e-02 1.4121729e-02]]
Open_eye
1/1 [==============================] - 0s 21ms/step
[[1.3069084e-04 4.2732584e-01 4.9660507e-01 6.2638178e-02 1.3300211e-02]]
Open_eye
1/1 [==============================] - 0s 21ms/step
[[5.1088668e-05 1.0354908e-01 8.6275762e-01 2.6591441e-02 7.0508383e-03]]
Open_eye
1/1 [==============================] - 0s 20ms/step
[[1.1302939e-04 4.3429312e-01 5.3696465e-01 2.0506680e-02 8.1224348e-03]]
Open_eye
1/1 [==============================] - 0s 21ms/step
[[4.7214115e-05 6.8136394e-01 3.0777147e-01 6.4015477e-03 4.4158236e-03]]
Open_eye
1/1 [==============================] - 0s 21ms/step
[[4.7393882e-05 7.9067481e-01 1.9594158e-01 9.4618378e-03 3.8744083e-03]]
Open_eye
1/1 [==============================] - 0s 20ms/step
[[9

[[4.0342048e-04 4.2867619e-01 2.6430666e-01 2.7751976e-01 2.9094128e-02]]
No_Yawn
1/1 [==============================] - 0s 21ms/step
[[0.00039688 0.38707098 0.35000232 0.23835462 0.02417519]]
Open_eye
1/1 [==============================] - 0s 21ms/step
[[2.4916546e-04 4.4678876e-01 4.3643236e-01 9.5508091e-02 2.1021605e-02]]
Closed_eye
1/1 [==============================] - 0s 20ms/step
[[2.5840881e-04 5.8002454e-01 2.0640396e-01 1.9516869e-01 1.8144531e-02]]
No_Yawn
1/1 [==============================] - 0s 22ms/step
[[3.4825780e-04 5.7053119e-01 1.8723680e-01 2.2246318e-01 1.9420596e-02]]
No_Yawn
1/1 [==============================] - 0s 21ms/step
[[2.9824636e-04 3.1252697e-01 6.2248957e-01 4.2964019e-02 2.1721167e-02]]
Open_eye
1/1 [==============================] - 0s 21ms/step
[[1.9841139e-07 9.9960631e-01 2.3441436e-04 5.5083383e-05 1.0404693e-04]]
Open_eye
1/1 [==============================] - 0s 20ms/step
[[0.00048016 0.32611278 0.16854008 0.47173056 0.03313654]]
1/1 [=======

1/1 [==============================] - 0s 23ms/step
[[2.7655161e-04 8.9359000e-02 8.1760550e-01 7.4427143e-02 1.8331788e-02]]
Open_eye
1/1 [==============================] - 0s 22ms/step
[[4.39586875e-04 1.25720739e-01 7.37597883e-01 1.10882774e-01
  2.53589526e-02]]
Open_eye
1/1 [==============================] - 0s 22ms/step
[[2.1331882e-04 1.4524302e-01 6.1430115e-01 2.2299729e-01 1.7245140e-02]]
Open_eye
1/1 [==============================] - 0s 30ms/step
[[3.2056391e-04 2.1002036e-01 6.4256078e-01 1.2598571e-01 2.1112572e-02]]
Open_eye
1/1 [==============================] - 0s 23ms/step
[[6.1072613e-05 9.2255734e-03 9.4998664e-01 3.1346198e-02 9.3805874e-03]]
Open_eye
1/1 [==============================] - 0s 22ms/step
[[2.6653698e-04 4.6597283e-02 6.2050277e-01 2.9513028e-01 3.7503161e-02]]
Open_eye
1/1 [==============================] - 0s 27ms/step
[[1.63514807e-04 3.77562940e-02 9.37470913e-01 1.17606325e-02
  1.28486436e-02]]
Open_eye
1/1 [==============================] - 0s

KeyboardInterrupt: 

In [12]:
cap.release()
cv2.destroyAllWindows()